// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// block_calculation_parallel
List block_calculation_parallel(List blocks);
RcppExport SEXP _PTL_PRS_c_block_calculation_parallel(SEXP blocksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type blocks(blocksSEXP);
    rcpp_result_gen = Rcpp::wrap(block_calculation_parallel(blocks));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_BedFileReader_module();

static const R_CallMethodDef CallEntries[] = {
    {"_PTL_PRS_c_block_calculation_parallel", (DL_FUNC) &_PTL_PRS_c_block_calculation_parallel, 1},
    {"_rcpp_module_boot_BedFileReader_module", (DL_FUNC) &_rcpp_module_boot_BedFileReader_module, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_PTL_PRS_c(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
