# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

block_calculation_parallel <- function(blocks) {
    .Call(`_PTL_PRS_c_block_calculation_parallel`, blocks)
}

